### ISSUE TITLE
Add location tracking during run

### ISSUE THREAD

**Issue by wrh17b** [Runner-s-High/runners-high-app#15]
* [ ] Location tracking w/ google fused location provider
* [ ] have service run in background
* [ ] make service work
